[package]
name = "cscrapper"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { workspace = true, features = ["blocking", "json"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
scraper = { workspace = true }
