[workspace]
members = [
  "cpast",
  "clex_gen",
  "cpastord", 
  "cscrapper", 
  "clex_llm", 
  "ccode_runner",
  "cpast_api"
]
resolver = "3"

[workspace.package]
authors = ["rootCircle <dev.frolics@gmail.com>"]
edition = "2024"
license = "GPL-3.0-or-later"
repository = "https://github.com/rootCircle/cpast_mono"
homepage = "https://rootcircle.github.io/blog/project/cpast.html"
rust-version = "1.85"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true  # Automatically strip symbols from the binary.

[workspace.dependencies]
actix-session = { version = "0.10.1", features = ["redis-session-rustls"] }
actix-web = "4.9.0"
actix-web-flash-messages = { version = "0.5.0", features = ["cookies"] }
anyhow = "1.0.96"
argon2 = { version = "0.5.3", features = ["std"] }
base64 = "0.22.1"
chrono = { version = "0.4.40", default-features = false, features = ["clock"] }
claims = "0.8.0"
cli-clipboard = { version = "0.4.0" }
clap = { version = "4.5.31", features = ["derive"] }
clap_complete = "4.5.46"
colored = "3.0.0"
config = { version = "0.15.8", default-features = false, features = ["yaml"] }
fake = "3.1.0"
futures = "0.3.31"
google-generative-ai-rs = { version = "0.3.4", features = ["beta"] }
hex = "0.4.3"
log = "0.4.25"
linkify = "0.10"
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
rand = "0.8.5"
regex = "1.11.1"
reqwest = { version = "0.12.12", default-features = false, features = [
    "json",
    "rustls-tls",
    "cookies",
] }
scraper = "0.22.0"
serde = { version = "1.0.218", features = ["derive"] }
serde-aux = "4.6.0"
serde_json = "1.0.139"
serde_urlencoded = "0.7.1"
secrecy = { version = "0.10.3", features = ["serde"] }
serenity = { version = "0.12.4", default-features = false, features = ["client", "gateway", "rustls_backend", "model"] }
sha2 = "0.10.8"
shuttle-runtime = "0.52.0"
shuttle-serenity = "0.52.0"
sqlx = { version = "0.8.3", default-features = false, features = [
    "runtime-tokio-rustls",
    "macros",
    "postgres",
    "uuid",
    "chrono",
    "migrate",
] }
tempfile = "3.18.0"
thiserror = "2.0.12"
tokio = { version = "1.43.0", features = ["full"] }
tracing = "0.1.41"
tracing-actix-web = "0.7.15"
tracing-bunyan-formatter = { version = "0.3.10" }
tracing-log = "0.2.0"
tracing-subscriber = { version = "0.3.19", features = ["registry", "env-filter"] }
unicode-segmentation = "1.12.0"
validator = "0.20.0"
wiremock = "0.6.2"
which = "7.0.2"
utoipa = { version = "5.3.1", features = [ "actix_extras" ] }
utoipa-swagger-ui = { version = "9.0.0", features = ["actix-web", "vendored"] }
utoipa-redoc = { version = "6.0.0", features = ["actix-web"] }
utoipa-rapidoc = { version = "6.0.0", features = ["actix-web"] }
utoipa-scalar = { version = "0.3.0", features = ["actix-web"] }
uuid = { version = "1.15.1", features = ["v4", "serde", "v7"] }
criterion = "0.5.1" 
