[package]
name = "code_companion"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.7", features = ["derive"] }
rand = "0.8.5"
unicode-segmentation = "1.10.1"
which = "5.0.0"
