[package]
name = "cpast"
version = "0.2.0"
edition = "2021"
license = "GPL-3"
repository = "https://github.com/rootCircle/code_companion"
description = "Run custom testcase with powerful clex lang powered generated tool. Ideal for competitive coders. Can test two file and pass & match randomly generated outputs"
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.7", features = ["derive"] }
rand = "0.8.5"
unicode-segmentation = "1.10.1"
which = "5.0.0"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3