[package]
name = "cpast"
version = "0.3.4"
edition = "2021"
license = " GPL-3.0-or-later"
authors = ["rootCircle <dev.frolics@gmail.com>"]
repository = "https://github.com/rootCircle/cpast"
description = "Run custom testcase with powerful clex lang powered generated tool. Ideal for competitive coders. Can test two file and pass & match randomly generated outputs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.18", features = ["derive"] }
cli-clipboard = { version = "0.4.0", optional = true }
rand = "0.8.5"
unicode-segmentation = "1.10.1"
which = "6.0.0"
tokio = { version = "1.35.1", features = ["full"] }
futures = "0.3.30"
colored = "2.1.0"

[features]
default = ["clipboard"]
clipboard = ["dep:cli-clipboard"]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true  # Automatically strip symbols from the binary.


