[workspace]
members = [
  "cpast",
  "clex",
  "cpastord"
  # "clex_llm",
, "cscrapper", "clex_llm", "ccode_runner"]
resolver = "2"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true  # Automatically strip symbols from the binary.

