[package]
name = "code_companion"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.7", features = ["derive"] }
regex = "1.10.2"
unicode-segmentation = "1.10.1"
which = "5.0.0"
