application:
  hmac_secret: super-long-and-secret-random-key-needed-to-verify-message-integrity
  host: 0.0.0.0
  port: 8000
database:
  database_name: newsletter
  host: 127.0.0.1
  password: password
  port: 5432
  require_ssl: false
  username: postgres
email_client:
  authorization_token: my-secret-token
  base_url: localhost
  sender_email: test@gmail.com
  timeout_milliseconds: 10000
llm:
  api_key: my-secret-key
redis_uri: redis://127.0.0.1:6379
