application:
  hmac_secret: super-long-and-secret-random-key-needed-to-verify-message-integrity
  host: 0.0.0.0
  port: 8000
database:
  database_name: cpast_store_db 
  host: 127.0.0.1
  password: password
  port: 5432
  require_ssl: false
  username: postgres
llm:
  api_key: my-secret-key
redis_uri: redis://127.0.0.1:6379
