name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Format
      run: cargo fmt --all --check 
    
    - name: Build cpast
      run: cargo build -p cpast --no-default-features --verbose
    
    - name: Build exclude cpast
      run: cargo build --workspace --exclude cpast --all-features --all-targets
    
    - name: Clippy cpast
      run: cargo clippy -p cpast --no-default-features -- -D warnings
    
    - name: Clippy exclude cpast
      run: cargo clippy --workspace --exclude cpast --all-features --all-targets -- -D warnings
    
    - name: Run tests
      run: cargo test --all-features --all-targets -- --skip send_to_clipboard_works
